# Generated by Django 5.2.7 on 2025-11-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_selections', to='events.formdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_screenshots', to='events.eventselection')),
            ],
        ),
        migrations.CreateModel(
            name='SeatSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_selections', to='events.eventselection')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.seat')),
            ],
        ),
    ]
