# Generated by Django 5.2.7 on 2025-12-03 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seat_price_selectedseat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscreenshot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.landingformdata'),
        ),
    ]
