# Generated by Django 5.2.7 on 2025-12-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentscreenshot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to='core.landingformdata'),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('held', 'Temporarily Held'), ('booked', 'Booked')], default='available', max_length=20),
        ),
    ]
